### ISSUE TITLE
The theme doenst work

### ISSUE THREAD

**Issue by Darkcast** [hmrserver/CTFd-theme-pixo#1]
Hi, 

I am running CTFd 3.3.0 locally on my machine (not in a docker) and I put the themes into the theme folder and I choose the theme but it doesnt load it just loads the generic core theme

**Comment by hmrserver** [comment]
Is your CTFd folder is same as:
`/opt/CTFd/CTFd/`
Please check, for hint there would be a core folder at
`/opt/CTFd/CTFd/themes/`
If not then locate the correct CTFd/themes folder and create a pixo folder there and paste all the GitHub files inside the pixo folder.
