### ISSUE TITLE
Challenge connection info not displayed

### ISSUE THREAD

**Issue by x1mus** [hmrserver/CTFd-theme-pixo#3]
Hello !
I'm just pointing out that "connection infos" are not displayed when your add them to a challenge.
(Maybe just an error ? Maybe it was intended ?)

**Comment by hmrserver** [comment]
A screenshot of the same would be appreciated.

**Comment by x1mus** [comment]
Well, this is hard to actually screenshot something that does not appear but I'll try my best then ...
![image](https://user-images.githubusercontent.com/26910323/149953751-4320aa71-0dcf-4eaa-8851-ff18c902e06a.png)
![image](https://user-images.githubusercontent.com/26910323/149953773-33939912-3c01-4d93-a671-747160e3f65d.png)
As you can see "github.com" does not display anywhere
